/**:
  ros__parameters:
    # Serial communication
    serial:
      port: "/dev/ttyUSB1"
      baud_rate: 115200

    demo_bot:
      pose_poll_interval_s: 1.0
      status_publish_interval_s: 0.5
      door_a_x: 1.2
      door_a_y: 0.0
      door_b_x: 0.0
      door_b_y: 0.0
      dock_x: 0.0
      dock_y: 0.0
      door_b_patrol_points: [0.0, 0.0, 0.25, 0.0, 0.25, 0.25, 0.0, 0.25]
